/**
 * tests/form-builder/repeating-section.test.ts
 *
 * Phase 14, Plan 02 — Nesting, value-shape, and validation coverage for repeatingSectionEntity.
 *
 * Structural template: tests/form-builder/section-reparent.spike.test.ts (Phase 13 spike).
 *
 * IMPORTANT — Per-instance validation gap (RESEARCH Open Question #1):
 * coltorapps validateEntitiesValues does NOT recurse into the instances[] array.
 * Per-instance child field validation must happen:
 *   (a) In the renderer before calling setEntityValue() (renderer-enforced, Plan 14-05), and
 *   (b) Ideally in an explicit server-side loop in submitAssessmentAction (Plan 14-03 or follow-up).
 * This test file documents the gap; closing it is tracked separately in the threat register (T-14-02-03).
 *
 * UUID note: coltorapps rejects arbitrary string IDs (Phase 13 13-01 SUMMARY deviation #4).
 * All entity IDs are generated by builderStore.addEntity() (which uses crypto.randomUUID() internally).
 */
import { describe, it, expect } from "vitest";
import { createBuilderStore, createInterpreterStore } from "@coltorapps/builder";

// ============================================================
// Nesting tests (setEntityParent / unsetEntityParent API)
// ============================================================

describe("repeatingSectionEntity — nesting API", () => {
  it("setEntityParent moves child textField out of root and into repeatingSection.children", async () => {
    const { formBuilder } = await import("@/lib/form-builder/index");
    const builderStore = createBuilderStore(formBuilder);

    const { id: repId } = builderStore.addEntity({
      type: "repeatingSection",
      attributes: { title: "Fire Doors", description: "", minInstances: 0 },
    });

    const { id: textId } = builderStore.addEntity({
      type: "textField",
      attributes: {
        label: "Door Location",
        required: false,
        placeholder: "",
        helpText: "",
        prefillSource: "",
      },
    });

    // Initially both are in root
    expect(builderStore.getSchema().root).toContain(repId);
    expect(builderStore.getSchema().root).toContain(textId);

    // Nest the textField inside the repeatingSection
    builderStore.setEntityParent(textId, repId);

    const schema = builderStore.getSchema();

    // repeatingSection remains in root
    expect(schema.root).toContain(repId);

    // textField is NO LONGER in root
    expect(schema.root).not.toContain(textId);

    // repeatingSection.children contains the textField
    expect(schema.entities[repId]?.children).toContain(textId);

    // textField.parentId points to the repeatingSection
    expect(schema.entities[textId]?.parentId).toBe(repId);
  });

  it("unsetEntityParent returns child textField to root", async () => {
    const { formBuilder } = await import("@/lib/form-builder/index");
    const builderStore = createBuilderStore(formBuilder);

    const { id: repId } = builderStore.addEntity({
      type: "repeatingSection",
      attributes: { title: "Rooms", description: "" },
    });
    const { id: textId } = builderStore.addEntity({
      type: "textField",
      attributes: { label: "Room Name", required: false, placeholder: "", helpText: "", prefillSource: "" },
    });

    builderStore.setEntityParent(textId, repId);
    expect(builderStore.getSchema().root).not.toContain(textId);

    builderStore.unsetEntityParent(textId);
    const schema = builderStore.getSchema();

    // Child is back in root
    expect(schema.root).toContain(textId);
    // No longer in parent's children
    expect(schema.entities[repId]?.children).not.toContain(textId);
    // parentId is cleared
    expect(schema.entities[textId]?.parentId).toBeUndefined();
  });

  it("childrenAllowed: true — can nest multiple children in repeatingSection", async () => {
    const { formBuilder } = await import("@/lib/form-builder/index");
    const builderStore = createBuilderStore(formBuilder);

    const { id: repId } = builderStore.addEntity({
      type: "repeatingSection",
      attributes: { title: "Items", description: "" },
    });
    const { id: child1Id } = builderStore.addEntity({
      type: "textField",
      attributes: { label: "Field A", required: false, placeholder: "", helpText: "", prefillSource: "" },
    });
    const { id: child2Id } = builderStore.addEntity({
      type: "numberField",
      attributes: { label: "Field B", required: false },
    });

    // Nesting both should succeed (childrenAllowed: true)
    expect(() => {
      builderStore.setEntityParent(child1Id, repId);
      builderStore.setEntityParent(child2Id, repId);
    }).not.toThrow();

    const schema = builderStore.getSchema();
    expect(schema.entities[repId]?.children).toContain(child1Id);
    expect(schema.entities[repId]?.children).toContain(child2Id);
  });

  it("setEntityParent into a textField (childrenAllowed: false) throws", async () => {
    const { formBuilder } = await import("@/lib/form-builder/index");
    const builderStore = createBuilderStore(formBuilder);

    const { id: textParentId } = builderStore.addEntity({
      type: "textField",
      attributes: { label: "Parent", required: false, placeholder: "", helpText: "", prefillSource: "" },
    });
    const { id: childId } = builderStore.addEntity({
      type: "textField",
      attributes: { label: "Child", required: false, placeholder: "", helpText: "", prefillSource: "" },
    });

    // textField has childrenAllowed: false (default), so nesting should throw
    expect(() => {
      builderStore.setEntityParent(childId, textParentId);
    }).toThrow();
  });
});

// ============================================================
// Value-shape round-trip (D-04 anti-regression)
// ============================================================

describe("repeatingSectionEntity — value-shape round-trip (D-04)", () => {
  it("stores and retrieves {instances: [{childA, childB}, {childA}]} unchanged", async () => {
    const { formBuilder } = await import("@/lib/form-builder/index");
    const builderStore = createBuilderStore(formBuilder);

    // Build a schema with one repeatingSection containing two child text fields
    const { id: repId } = builderStore.addEntity({
      type: "repeatingSection",
      attributes: { title: "Entries", description: "", minInstances: 0 },
    });
    const { id: childAId } = builderStore.addEntity({
      type: "textField",
      attributes: { label: "Field A", required: false, placeholder: "", helpText: "", prefillSource: "" },
    });
    const { id: childBId } = builderStore.addEntity({
      type: "textField",
      attributes: { label: "Field B", required: false, placeholder: "", helpText: "", prefillSource: "" },
    });
    builderStore.setEntityParent(childAId, repId);
    builderStore.setEntityParent(childBId, repId);

    const schema = builderStore.getSchema();
    const interpreterStore = createInterpreterStore(formBuilder, schema);

    // Set a multi-instance value matching the D-04 shape
    const instancesValue = {
      instances: [
        { [childAId]: "aaa", [childBId]: "bbb" },
        { [childAId]: "ccc" },
      ],
    };

    interpreterStore.setEntityValue(repId, instancesValue);

    const values = interpreterStore.getEntitiesValues();
    expect(values[repId]).toEqual(instancesValue);
  });
});

// ============================================================
// validate() container shape tests
// ============================================================

describe("repeatingSectionEntity.validate() — container shape", () => {
  it("returns the value unchanged when instances is a valid non-empty array", async () => {
    const { repeatingSectionEntity } = await import(
      "@/lib/form-builder/entities/repeating-section"
    );
    const input = { instances: [{}, {}, {}] };
    const result = repeatingSectionEntity.validate(input, {} as never);
    expect(result).toEqual(input);
  });

  it("throws with 'instances' in the error message when instances is not an array", async () => {
    const { repeatingSectionEntity } = await import(
      "@/lib/form-builder/entities/repeating-section"
    );
    expect(() =>
      repeatingSectionEntity.validate({ instances: 42 } as never, {} as never)
    ).toThrow(/instances/);
  });
});

// ============================================================
// Per-instance validation gap — documented (RESEARCH Open Question #1)
// ============================================================

describe("per-instance validation gap — documented", () => {
  it.todo(
    "validateEntitiesValues succeeds even when an instance has an invalid required child value — per-instance validation deferred to renderer (Plan 14-05) and submitAssessmentAction (T-14-02-03)"
  );

  /**
   * Explanation of the gap (for future implementers):
   *
   * coltorapps validateEntitiesValues() only validates the TOP-LEVEL entity shape.
   * For repeatingSection, this means it validates that the container value matches
   * the entity's validate() function (i.e., { instances: [] } shape) — but it does
   * NOT iterate over each instance to check child field values.
   *
   * Consequence: a submission with { instances: [{ childId: "" }] } where childId is
   * a required textField WILL pass coltorapps's server-side validation. The renderer
   * in Plan 14-05 must enforce this before calling setEntityValue(). A server-side loop
   * in submitAssessmentAction should also validate per-instance child values.
   *
   * Auth gate: the assessment surface is admin-only (requireActorUserId("admin")).
   * This provides a primary security control while the per-instance gap remains open.
   */
});

// ============================================================
// D-03 min/max bounds — schema-level documentation
// ============================================================

describe("D-03 min/max bounds — schema-level note", () => {
  it("entity.validate() returns OK for instances below minInstances (bounds enforced by renderer)", async () => {
    const { repeatingSectionEntity } = await import(
      "@/lib/form-builder/entities/repeating-section"
    );
    // Set minInstances = 2 in the attrs; validation with only 1 instance should still pass
    // at the entity level. The renderer enforces min/max before calling setEntityValue().
    // This is intentional: entity.validate() checks SHAPE, not BUSINESS RULES.
    const val = { instances: [{}] }; // length 1, below minInstances = 2
    const result = repeatingSectionEntity.validate(val, {
      entity: { attributes: { minInstances: 2 } },
    } as never);
    // Should return the value unchanged — bounds are renderer-enforced
    expect(result).toEqual(val);
  });
});
